# Generated by Django 5.2.6 on 2025-10-02 10:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Дата и время отправки пожертвования', verbose_name='Дата и время')),
                ('amount', models.PositiveIntegerField(help_text='Сумма пожертвования', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сумма')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Скрытая сумма пожертвования', verbose_name='Скрытая')),
                ('collect', models.ForeignKey(help_text='Сбор, к которому относится пожертвование', on_delete=django.db.models.deletion.CASCADE, to='collects.collect', verbose_name='Сбор')),
            ],
        ),
    ]
