# Generated by Django 5.2.6 on 2025-10-03 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0002_initial'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='collect',
            field=models.ForeignKey(help_text='Сбор, к которому относится пожертвование', on_delete=django.db.models.deletion.CASCADE, related_name='donor', to='collects.collect', verbose_name='Сбор'),
        ),
    ]
