# Generated by Django 5.2.6 on 2025-10-02 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Названия сбора', max_length=254, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Название')),
                ('reason', models.CharField(choices=[('PLATFORM', 'Развитие'), ('COMMUNITY', 'Мероприятие'), ('CHARITY', 'Благотворительность')], help_text='Повод сбора пожертвований', max_length=30, verbose_name='Повод')),
                ('description', models.TextField(blank=True, help_text='Описание цели сбора пожертвований', null=True, verbose_name='Описание')),
                ('total_goal_amount', models.PositiveBigIntegerField(blank=True, help_text='Планируемый сбор пожертвований', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Планируемый сбор')),
                ('image', models.ImageField(blank=True, help_text='Обложка сбора пожертвований', null=True, upload_to='', verbose_name='Обложка')),
                ('date_end', models.DateTimeField(help_text='Время окончания сбора пожертвований', verbose_name='Время окончания')),
                ('target_amount', models.PositiveIntegerField(help_text='Цель для количества пожертвований', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цель пожертвований')),
            ],
        ),
    ]
